merge_queue:
  max_parallel_checks: 2
  skip_intermediate_results: false
  mode: isolated

queue_rules:
  - name: vm4-cr-overlap-lastwins-target-261003
    batch_size: 2
    batch_max_wait_time: 2 sec
    merge_method: merge-batch
    conflict_resolvers:
      - paths:
          - sensitive-*
        strategy: theirs
      - paths:
          - sensitive-default.txt
        strategy: ours
    queue_conditions:
      - title = VM4 CR OVERLAP LASTWINS TARGET 261003
    merge_conditions:
      - check-success = vm4-never-cr-overlap-order
